# Use Maven to build a Debian installer for Gamma

name: Build Unix Installer

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17.0.2
        distribution: 'temurin'
        cache: 'maven'
    - name: Build with Maven
      run: mvn -B clean package
    - uses: actions/upload-artifact@v3
      with:
        name: Debian X64 Package
        path: ./target/*.deb
        if-no-files-found: error