# Use Maven to build a MacOS 11 x64 installer for Gamma

name: Build MacOS Installer

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17.0.2
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B clean package
      - uses: actions/upload-artifact@v3
        with:
          name: MacOS X64 Package
          path: ./target/*.dmg
          if-no-files-found: error